### ISSUE TITLE
Support automatic PV deletion and storage cleanup with reclaimPolicy: Delete

### ISSUE THREAD

**Issue by kaeltis** [kubernetes-csi/csi-driver-nfs#111]
**Is your feature request related to a problem?/Why is this needed**
According to the example files this CSI Driver (which seems to be the only one available for NFS) only supports `reclaimPolicy: Retain`, if I understand correctly this means after deleting a PVC it's associated PV has to be removed manually and even after removing the PV the created files and directories are not deleted from the NFS target server.

**Describe the solution you'd like in detail**
I'd love if this driver could implement `reclaimPolicy: Delete` and proper cleanup of PVs, so when a PVC is deleted, the associated PV and files/folders on the NFS server would be deleted as well.

**Describe alternatives you've considered**
I've thought about somehow automating the process of regularly cleaning unbound PVs and deleting the associated directories on the NFS server, but this doesn't seem like a great solution

**Comment by msau42** [comment]
This will be supported with https://github.com/kubernetes-csi/csi-driver-nfs/issues/30

We have not released a driver yet with this change, but you can try it out on canary.

**Comment by kaeltis** [comment]
Ah, missed that, thanks!
