### ISSUE TITLE
production ready and external NFS support .

### ISSUE THREAD

**Issue by eliyahu77** [kubernetes-csi/csi-driver-nfs#114]
HI * ,

I want to know if there any target that the nfs plugin will be supported on k8s for production envs.

and i want to know also if this plugin supported external nfs v4/ nfs v3 , that not installed on the k8s cluster .

BR Eliyahu

**Comment by andyzhangx** [comment]
currently this project is still alpha, and we will publish a beta release soon. GA time could be later, not decided yet.

**Comment by andyzhangx** [comment]
and about nfs v4/ nfs v3 support, this driver should supports both, there is no hardcoded setting in this driver so both protocols should be supported.

**Comment by johnsimcall** [comment]
> and i want to know also if this plugin supported external nfs v4/ nfs v3 , that not installed on the k8s cluster .

Hi csi-driver-nfs! I have this same question. Your README says:

> This driver requires existing and already configured NFSv3 or NFSv4 server... 

but there is nowhere to specify the FQDN/IP address and path of my NFS server. Instead it appears to me that this project creates an NFS server inside a Kubernetes cluster. Have I misunderstood?

**Comment by andyzhangx** [comment]
creating an NFS server inside a k8s cluster is just an example: https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/deploy/example/nfs-provisioner/README.md, it's actually out of this csi driver's scope.

I refined the example doc a little: https://github.com/kubernetes-csi/csi-driver-nfs/tree/master/deploy/example#storage-class-usage-dynamic-provisioning
