### ISSUE TITLE
mixed clusters (windows+linux)

### ISSUE THREAD

**Issue by malikumaliku** [kubernetes-csi/csi-driver-nfs#116]
I am doing some tests with this diver and Helm on a windows+linux cluster.
However, the csi-nfs-node also gets triggered on windows nodes.

Could you hardcore a node selector for csi-nfs-node, or have a way to set a nodeselector via a Helm config override?

**Comment by andyzhangx** [comment]
@dr0pdb could you help? could refer to setting in smb driver.

**Comment by dr0pdb** [comment]
@andyzhangx @malikumaliku  
I think https://github.com/kubernetes-csi/csi-driver-nfs/pull/117 fixed this issue. We do have a node selector specified to deploy only on Linux nodes.

**Comment by malikumaliku** [comment]
fix confirmed
