### ISSUE TITLE
enable spelling and boilerplate check 

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/csi-driver-nfs#128]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

https://github.com/kubernetes-csi/csi-driver-nfs/pull/127 disabled following two checks:
 - verify-spelling.sh
 - verify-boilerplate.sh

need to upstream the above two scripts to https://github.com/kubernetes-csi/csi-release-tools.git and then re-enable these two scripts in this project

**Describe alternatives you've considered**

**Additional context**

```
error: docs/csi-dev.md:38:12: "environmnet" is a misspelling of "environments"
error: docs/csi-dev.md:89:6: "environmnet" is a misspelling of "environments"
error: release-tools/SIDECAR_RELEASE_PROCESS.md:14:17: "maintainence" is a misspelling of "maintenance"
error: release-tools/prow.sh:76:31: "seperately" is a misspelling of "separately"
error: release-tools/prow.sh:296:37: "seperated" is a misspelling of "separated"
error: release-tools/prow.sh:1001:32: "succesful" is a misspelling of "successful"
Found spelling errors!
Cleaning up...
Makefile:46: recipe for target 'verify' failed
make: *** [verify] Error 1
Error: Process completed with exit code 2.
```

**Comment by andyzhangx** [comment]
@sachinkumarsingh092 could you help? thanks.

**Comment by sachinkumarsingh092** [comment]
So we just have to push the `hack/boilerplate`, `hack/verify-spellcheck.sh` and `hack/boilerplate.sh` to https://github.com/kubernetes-csi/csi-release-tools.git, modify the `build.make` there to include these tests and after this is merged we can `git subtree pull` it for out repo. It this correct or am I missing something?

/assign

**Comment by andyzhangx** [comment]
> So we just have to push the `hack/boilerplate`, `hack/verify-spellcheck.sh` and `hack/boilerplate.sh` to https://github.com/kubernetes-csi/csi-release-tools.git, modify the `build.make` there to include these tests and after this is merged we can `git subtree pull` it for this repo. Is this correct or am I missing something?
> 
> /assign

correct, thanks.
