### ISSUE TITLE
Tests fail on NixOS

### ISSUE THREAD

**Issue by MagicRB** [kubernetes-csi/csi-driver-nfs#132]
**What happened**:
Test case `test/e2e/e2e_suite_test.go:157` fails when buiding with Nix

**What you expected to happen**:
I expected tests to succeed as checking if the project directory ends in `csi-driver-nfs` doesn't make sense

**How to reproduce it**:
Try to build `csi-driver-nfs` on NixOS with `pkgs.buildGoModule` and you'll encounter this fun bug

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: N/A
- Kubernetes version (use `kubectl version`): N/A
- OS (e.g. from /etc/os-release): NixOS
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Recommended Fix**:
Delete that line

**Comment by andyzhangx** [comment]
hi @MagicRB would you submit a PR directly? thanks.

**Comment by andyzhangx** [comment]
and you could also contribute how to build this project in NixOS

**Comment by MagicRB** [comment]
I really don't want to go through the license agreement stuff, so unfortunately not at this time

**Comment by andyzhangx** [comment]
while I don't have NixOS, not sure how to fix this.

**Comment by MagicRB** [comment]
and another issue has cropped up, `test/e2e/e2e_suite_test.go:26:2: imported and not used: "strings"` which is really an easy fix as the first one. And as to NixOS building, that should really go into [nixpkgs](https://github.com/NixOS/nixpkgs), which I'll do at some point.
> while I don't have NixOS, not sure how to fix this.
there really only two things, which we can do, either delete that project name check or disable tests as I can't tell Nix to use a different folder, it would break the pureness of the build process.

**Comment by andyzhangx** [comment]
cc @dr0pdb

**Comment by MagicRB** [comment]
BTW, I pushed the Docker container builder to my Gitea [instance](https://gitea.redalder.org/RedAlder/systems), the builder builds this driver from Nix. It's easy to extract the Nix package from that. The advantage over regular Dockerfiles is truly reproducible builds and (generally) smaller images, seems to not be that pronounced with go apps
