### ISSUE TITLE
PVC not provsioned because file exists

### ISSUE THREAD

**Issue by viktoriaas** [kubernetes-csi/csi-driver-nfs#154]
**What happened**:
I deployed PVC with deployment and PVC did not create although the directory on NFS server was created. 

**What you expected to happen**:
The PVC gets created

**How to reproduce it**:
It's an unstable behaviour, sometimes it happens and sometimes not. Today I deployed 4 PVCs at once and one of them ended in this state. Logs:
```
I0209 16:15:51.630511       1 mount_linux.go:146] Mounting cmd (mount) with arguments (-t nfs -o hard,nfsvers=3,nolock 147.251.6.50:/gpfs/vol1/nfs/wes /tmp/pvc-41b9c53e-a0fc-4131-a020-9db9de970342)
I0209 16:15:52.728172       1 controllerserver.go:267] internally unmounting /tmp/pvc-41b9c53e-a0fc-4131-a020-9db9de970342
I0209 16:15:52.728411       1 nodeserver.go:120] NodeUnpublishVolume: CleanupMountPoint /tmp/pvc-41b9c53e-a0fc-4131-a020-9db9de970342 on volumeID(147.251.6.50/gpfs/vol1/nfs/wes/pvc-41b9c53e-a0fc-4131-a020-9db9de970342)
I0209 16:15:52.728528       1 mount_helper_common.go:71] "/tmp/pvc-41b9c53e-a0fc-4131-a020-9db9de970342" is a mountpoint, unmounting
I0209 16:15:52.728585       1 mount_linux.go:238] Unmounting /tmp/pvc-41b9c53e-a0fc-4131-a020-9db9de970342
I0209 16:15:53.344914       1 mount_helper_common.go:85] "/tmp/pvc-41b9c53e-a0fc-4131-a020-9db9de970342" is unmounted, deleting the directory
E0209 16:15:53.345448       1 utils.go:89] GRPC error: rpc error: code = Internal desc = failed to make subdirectory: mkdir /tmp/pvc-41b9c53e-a0fc-4131-a020-9db9de970342/pvc-41b9c53e-a0fc-4131-a020-9db9de970342: file exists
```

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: latest master 
- Kubernetes version (use `kubectl version`): v1.19.3
- OS (e.g. from /etc/os-release): CentOS Linux 8
- Kernel (e.g. `uname -a`): Linux  4.18.0-240.10.1.el8_3.x86_64
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
fixed by https://github.com/kubernetes-csi/csi-driver-nfs/pull/156, pls try master branch again, thanks.
