### ISSUE TITLE
Creating PVCs still results in memory fail

### ISSUE THREAD

**Issue by viktoriaas** [kubernetes-csi/csi-driver-nfs#158]
**What happened**:
Hi, 
in the end, doubling the memory limit didn't help. (#155 )
```
[16432189.299684] Memory cgroup out of memory: Killed process 3674331 (nfsplugin) total-vm:734676kB, anon-rss:8768kB, file-rss:18444kB, shmem-rss:0kB, UID:0
```
I wanted to create 4 PVCs. I resized to 1000Mi. It might be that the more PVCs you want to create at once, the more memory you need. This could be specified somewhere as some deployments are burstable and will have to create multiple PVCs at once

**What you expected to happen**:
create PVCs

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
I think we should set `nfs` memory limit as 1000Mi, not `csi-provisioner`
