### ISSUE TITLE
Docs: volumeAttributes clarification

### ISSUE THREAD

**Issue by chessman** [kubernetes-csi/csi-driver-nfs#171]
**What happened**:

[Here](https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/docs/driver-parameters.md) I see `volumeAttributes.source` parameter. But [here](https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/deploy/example/pv-nfs-csi.yaml) there is `volumeAttributes.server` instead.

**What you expected to happen**:

I guess, `volumeAttributes.server` is correct and `volumeAttributes.source` is not.

**Comment by andyzhangx** [comment]
it should be `server`, doc updated: https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/docs/driver-parameters.md
