### ISSUE TITLE
nfsv3 stat support

### ISSUE THREAD

**Issue by ghost** [kubernetes-csi/csi-driver-nfs#178]
When connecting to an NFS server and specifying the nfsvers=3 option the nfs logs complain that there is no support for locks.
Could it be possible to have also the statd/rpcbind service running in the nfs container?

`
E0321 16:55:41.811304       1 utils.go:91] GRPC error: rpc error: code = Internal desc = failed to mount nfs server: rpc error: code = Internal desc = mount failed: exit status 32
`
`
Mounting command: mount
`
`
Mounting arguments: -t nfs -o hard,nfsvers=3 192.168.123.1:/storage/irispulse-persistent /tmp/pvc-b84a1b5a-b769-469a-b452-835128d43a4a
`
`
Output: mount.nfs: rpc.statd is not running but is required for remote locking.
`
`
mount.nfs: Either use '-o nolock' to keep locks local, or start statd.
`
`
E0321 16:55:42.305061       1 mount_linux.go:150] Mount failed: exit status 32
`

**Comment by boddumanohar** [comment]
@malikumaliku could you please post the steps to reproduce this?

**Comment by LittleFox94** [comment]
I believe running the `rpc.statd` in the container could wreck havoc when the container is restarted -  from perspective of the NFS server it would look like the NFS client machine was rebooted, so held locks being gone is not a problem, but the filesystem is actually still mounted and applications accessing it think they still hold locks.
