### ISSUE TITLE
container image nfsplugin:v1.0.0 not found.

### ISSUE THREAD

**Issue by hwchiu** [kubernetes-csi/csi-driver-nfs#18]
The container image **quay.io/k8scsi/nfsplugin:v1.0.0** doesn't exist and we can only find **quay.io/k8scsi/nfsplugin:v0.2.0** in [quay.io/k8scsi/nfsplugin](https://quay.io/repository/k8scsi/nfsplugin).

According to the image tag history displayed from the quay page. I only see tag v0.2.0 and canary

**Comment by msau42** [comment]
This is being tracked by https://github.com/kubernetes-csi/csi-driver-nfs/issues/4
/close
