### ISSUE TITLE
Specify owner of NFS dir

### ISSUE THREAD

**Issue by xhejtman** [kubernetes-csi/csi-driver-nfs#183]
**Is your feature request related to a problem?/Why is this needed**

PV is owned by root:root with access rights either 0700 or 0777, none is good solution. Would it be possible to specify owner and rights of PV in PVC request?

You can use initcontainer if security policy is not applied, you are out of luck if it is applied.

**Comment by andyzhangx** [comment]
may use https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

**Comment by xhejtman** [comment]
I do not think this is an option. I cannot set runAsRoot (pod security in place) and volume is owned by root.

**Comment by xhejtman** [comment]
I do not think you can run chmod in initContainer as you cannot runAsRoot if podsecurity is in place, can you? However, the csi nfs driver creates the pvc dir and sets 0777 access rights on it (can be seen in the go code). Would it be possible to change the code so that it sets access rights and/or owner as set in PVC spec? I mean is it technically possible? Or there is no chance to add such an option to the PVC spec? 

It seems you need to add a new attribute PVC spec, e.g.:
fs:
   owner: 1000
   group: 1000    
   mode: 0770

and pass it to the csi driver but I am not sure, if it is valid.

**Comment by andyzhangx** [comment]
We can only add new parameters in storage class and then pass it in `CreateVolume` to set access rights
https://github.com/kubernetes-csi/csi-driver-nfs/blob/b53f765682fb8dc667e2869adf81200aead2a289/pkg/nfs/controllerserver.go#L103-L105

https://github.com/kubernetes-csi/csi-driver-nfs/blob/b53f765682fb8dc667e2869adf81200aead2a289/deploy/example/storageclass-nfs.yaml#L7-L9

**Comment by xhejtman** [comment]
So there is no chance to specify it in PVC (I mean with adding appropriate code to the CSI driver)?

Storage class is global, PVC is user specific so the user can choose which UID should be the owner.

**Comment by andyzhangx** [comment]
UID should be specified in mount process, while NFSv4 does not support set UID in mount, not sure how to achieve this 
cc @msau42 any idea?

**Comment by xhejtman** [comment]
the csi driver can run chown on its own as it runs in root context when creating the pvc dir, cannot it?

**Comment by andyzhangx** [comment]
> the csi driver can run chown on its own as it runs in root context when creating the pvc dir, cannot it?

I think yes, and there is a driver flag to set dir permission, I think we could add more parameters in driver to support self defined dir_mode, gid, uid, etc, will take a look later.

https://github.com/kubernetes-csi/csi-driver-nfs/blob/3e9ef1e80d7b32af5a14189fc5c052c561fce895/cmd/nfsplugin/main.go#L33

**Comment by msau42** [comment]
If gid is sufficient, then you can opt into fsgroup support: https://kubernetes-csi.github.io/docs/support-fsgroup.html

However with shared volumes like nfs, you need to be careful that all pods sharing it will have the same gid.

**Comment by xhejtman** [comment]
> I think yes, and there is a driver flag to set dir permission, I think we could add more parameters in driver storage class to support self defined dir_mode, gid, uid, etc for new created pvc dir, will take a look later.

nice, but this is useful only, if you can set dir permission in persistentvolumeclaim specification, because you would need to create new storage class for every permission and uid/gid you want to use, don't you?

we have one nfs storage class for all k8s users. Every user can create his own pvc spec to get dynamicaly providioned volume. So if you can specify permissions in storage class only, it will not address this issue.
