### ISSUE TITLE
confuse I want to ask is it recommended to use nfs in k8s?

### ISSUE THREAD

**Issue by hunterhug** [kubernetes-csi/csi-driver-nfs#231]
It is not recommended that you use NFS storage for production (especially on Kubernetes version 1.20 or later) as some issues may occur, such as failed to obtain lock and input/output error, resulting in Pod CrashLoopBackOff. Besides, some apps may not be compatible with NFS, including Prometheus.

as below says:

https://kubesphere.com.cn/en/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client/

**Comment by andyzhangx** [comment]
that article is about setting up a nfs server on local machine which is not suitable for production. While k8s nfs plugin is production ready.
