### ISSUE TITLE
Add extraLabels to K8s resources

### ISSUE THREAD

**Issue by JPRbrs** [kubernetes-csi/csi-driver-nfs#283]
**Is your feature request related to a problem?/Why is this needed**
I think that having the capability of adding extra labels to k8s resources created by the Helm chart would be advantageous. In my particular case, I'm using CSI-driver-NFS as a dependency and I'd like to label all resources with custom labels.

**Describe the solution you'd like in detail**
I have a small PR ready to add that functionality if the community considers it adequate

**Describe alternatives you've considered**
The change is quite small, I didn't consider any other alternatives

**Additional context**
N/A

The question should I modify files in csi-driver-nfs/charts/latest/csi-driver-nfs/ folder and push the pull request up?

Many thanks in advance, 
Javier

**Comment by andyzhangx** [comment]
yes, and you also need to run `cd charts/latest` && `helm package csi-driver-nfs`

**Comment by JPRbrs** [comment]
Many thanks @andyzhangx !!
