### ISSUE TITLE
Failed to install this driver on ppc64le arch

### ISSUE THREAD

**Issue by nanmor** [kubernetes-csi/csi-driver-nfs#288]
**What happened**:
Installed csi-driver-nfs
[root@alphabore csi-driver-nfs]# ./deploy/install-driver.sh master local
use local deploy
Installing NFS CSI driver, version: master ...
serviceaccount/csi-nfs-controller-sa created
clusterrole.rbac.authorization.k8s.io/nfs-external-provisioner-role created
clusterrolebinding.rbac.authorization.k8s.io/nfs-csi-provisioner-binding created
csidriver.storage.k8s.io/nfs.csi.k8s.io created
deployment.apps/csi-nfs-controller created
daemonset.apps/csi-nfs-node created
NFS CSI driver installed successfully.

but all pod failed.
for the controller part:
Failed to pull image "mcr.microsoft.com/k8s/csi/nfs-csi:latest": rpc error: code = Unknown desc = choosing image instance: no image found in manifest list for architecture ppc64le, variant "", OS linux
which image could use instead, this is record in [csi-nfs-controller.yaml](https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/deploy/csi-nfs-controller.yaml)

for node part:
Failed to pull image "k8s.gcr.io/sig-storage/livenessprobe:v2.5.0": rpc error: code = Unknown desc = Source image rejected: Running image docker://k8s.gcr.io/sig-storage/livenessprobe:v2.5.0 is rejected by policy.
Failed to pull image "k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.4.0": rpc error: code = Unknown desc = Source image rejected: Running image docker://k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.4.0 is rejected by policy.

**What you expected to happen**:
install successfully
**How to reproduce it**:

**Anything else we need to know?**:
**Environment**: openshift 4.9.21
- CSI Driver version: master
- Kubernetes version (use `kubectl version`): ubernetes Version: v1.22.3+fdba464
- OS (e.g. from /etc/os-release): NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
- Kernel (e.g. `uname -a`): Linux alphabore.rch.stglabs.ibm.com 4.18.0-193.el8.ppc64le #1 SMP Fri Mar 27 14:40:12 UTC 2020 ppc64le ppc64le ppc64le GNU/Linux
- Install tools:
- Others:
thanks a lot.

**Comment by andyzhangx** [comment]
that's `ppc64le` arch, not sure whether it's supported by all csi driver sidecar images

**Comment by nanmor** [comment]
I have found other images to replace them, thanks and close it.

**Comment by andyzhangx** [comment]
@nanmor what's the other images? could you provide more details?

**Comment by nanmor** [comment]
The image is from https://catalog.redhat.com/software/containers/openshift4/ose-csi-external-provisioner/5d934605d70cc50ebeaa337e?architecture=ppc64le&container-tabs=gti, and others also search from that website.
