### ISSUE TITLE
Add information to README for csi-driver-nfs

### ISSUE THREAD

**Issue by saad-ali** [kubernetes-csi/csi-driver-nfs#3]
Add the follow information:

* What version of CSI does this driver support
* What is the status of this driver (alpha).
* Which of the following (optional) features does this driver support:
   * dynamic provisioning
   * online resize or offline resize
   * block
   * snapshot
* Which AccessModes does this driver support?

/assign @prateekpandey14

**Comment by msau42** [comment]
@mathu97 could you help update the readme?

**Comment by mathu97** [comment]
@msau42 yes, will get on it.
