### ISSUE TITLE
Is it possible to implement snapshot functionality for nfs csi driver

### ISSUE THREAD

**Issue by LilyaBu** [kubernetes-csi/csi-driver-nfs#31]
Hello! Is it possible to implement snapshot functionality for nfs csi driver? May be same as hostpath csi driver.

**Comment by wozniakjan** [comment]
Hi, I believe it is possible but at the moment there is no plan to implement that quite yet. But if you'd like to take a stab at it, I will happily support you and review the code to get that merged.

**Comment by LilyaBu** [comment]
Thank you. I interested in csi nfs because i would like to backup/restore  persistent volumes as cluster resources, not as app resource. As i understand this can be realised with StorageClass objects.

**Comment by wozniakjan** [comment]
In the whole scheme of things, `StorageClass` definitely plays an important role, but it is rather connected with another feature - autoprovisioning of PVs.

Snapshots introduce own set of resources, https://kubernetes-csi.github.io/docs/snapshot-restore-feature.html is a great document to understand how snapshots under CSI work. This plugin will then need to figure out how to talk to the NFS server about supporting the second part of snapshots functionality.

**Comment by LilyaBu** [comment]
Thank you for links and explanation.

**Comment by wozniakjan** [comment]
/reopen
/assign

https://github.com/kubernetes-csi/csi-driver-nfs/issues/30#issuecomment-617496994 discusses an alternative direction to implement snapshots. I could see myself finding a little bit of time in following weeks to give that a shot.

**Comment by wozniakjan** [comment]
/remove-lifecycle rotten
hoping to have some time in September finally to work on this.

**Comment by guleng** [comment]
@wozniakjan Has the snapshot function been implemented for storage where NFS becomes PV?

**Comment by wozniakjan** [comment]
@guleng no, I couldn't find time, my apologies

**Comment by kamzata** [comment]
+1

**Comment by navilg** [comment]
+1

**Comment by fontexD** [comment]
+1

**Comment by chaotec** [comment]
+1

**Comment by mehdi-wsc** [comment]
+1

**Comment by wozniakjan** [comment]
resurrecting from the rotten land, taking small steps by proposing first draft on volume-to-volume clone https://github.com/kubernetes-csi/csi-driver-nfs/pull/426. If `cp -a` is an acceptable approach, would like to continue with proposing snapshots as tarballs stored in appropriate path on the NFS server, clone from snapshots could be similarly trivial then as `untar` to a proper PVC path.

**Comment by fontexD** [comment]
Sounds look a good idea!

**Comment by wozniakjan** [comment]
https://github.com/kubernetes-csi/csi-driver-nfs/pull/426 merged, I will try to see if I can implement and propose `tar` and `untar` snapshots now

**Comment by wozniakjan** [comment]
I would like to continue and propose the tarball snapshots in https://github.com/kubernetes-csi/csi-driver-nfs/pull/430, any comments and ideas are welcome.
