### ISSUE TITLE
[feature request] Add ability to parameterize subdirectory

### ISSUE THREAD

**Issue by semenodp** [kubernetes-csi/csi-driver-nfs#312]
**Is your feature request related to a problem?/Why is this needed**
With the current implementation, the subdirectory of nfs volume matches pvc name. However, I would like to be able to point the mount to the already existing subdirectory instead of creating a new directory in the root of nfs server. 

**Describe the solution you'd like in detail**
Would like to have subdir variable to be parameterized through parameters in storage class like it's done with server and baseDir

https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/pkg/nfs/controllerserver.go#L319

I am happy to pick up the work as it does not seem like a big change, but would like to hear if there are any drawbacks to parameterizing subdirectory.

**Comment by andyzhangx** [comment]
if you want to mount to existing subdir, why not use PV/PVC directly: https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/docs/driver-parameters.md#pvpvc-usage-static-provisioning
set `volumeAttributes.share` as `/subdir`, storage class is for dynamic provisioning while in your case, you don't need to create a new subdir.

**Comment by semenodp** [comment]
Ah, let me try to do that. I am still seeing Storage Class specified in both static pv and pvc, is that still necessary? 
https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/deploy/example/pv-nfs-csi.yaml#L12

**Comment by andyzhangx** [comment]
> Ah, let me try to do that. I am still seeing Storage Class specified in both static pv and pvc, is that still necessary? https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/deploy/example/pv-nfs-csi.yaml#L12

@semenodp that's optional, you could set a `storageClassName` or set as `storageClassName: ""`, which is only for PV/PVC binding

**Comment by semenodp** [comment]
I believe, that worked. Any advantage of using csi plugin over defining nfs field like it's done in kubernetes example (https://github.com/kubernetes/examples/blob/master/staging/volumes/nfs/nfs-pv.yaml) if doing static provisioning?

**Comment by andyzhangx** [comment]
> I believe that worked. Any advantage of using csi plugin over defining nfs field like it's done in kubernetes example (https://github.com/kubernetes/examples/blob/master/staging/volumes/nfs/nfs-pv.yaml) if doing static provisioning?

@semenodp there is no advantage in static provisioning now, while new features would be only added into this driver since the  built-in nfs plugin is in maintenance mode.
