### ISSUE TITLE
sticky bit not honored under mountPermissions

### ISSUE THREAD

**Issue by Elegant996** [kubernetes-csi/csi-driver-nfs#325]
At present, using sticky bit (setuid/setgid) under `mountPermissions` does not apply the correct permissions during `chmod`. Stick bit should be honored and applied so that the fsGroup has proper access.

Thanks!

**Comment by andyzhangx** [comment]
it works now?

**Comment by Elegant996** [comment]
Sorry, was refiling with proper bug report!
