### ISSUE TITLE
sticky bit not honored when mounting volume

### ISSUE THREAD

**Issue by Elegant996** [kubernetes-csi/csi-driver-nfs#326]
**What happened**:
Applied sticky bit under `mountPermissions` (i.e. `2770`) where `setgid` should be applied to the volume mount but only regular `chmod` permissions were applied (i.e. 0770).

**What you expected to happen**:
`setuid` and/or `setgid` should be honored and applied to the volume mount.

**How to reproduce it**:
Use sticky bit when mounting an NFS volume.

**Anything else we need to know?**:
This option should really only applies NFSv3 volumes but that would be up to the end user to decide.

**Environment**:
- CSI Driver version: 3.1.0
- Kubernetes version (use `kubectl version`): 1.23.4
- OS (e.g. from /etc/os-release): fedora-coreos-35.20220410.3.1
- Kernel (e.g. `uname -a`): 5.16.18
- Install tools: typhoon
- Others:

**Comment by andyzhangx** [comment]
we already support `fsGroupPolicy: File` which means gid should be set if it's defined in pod `securtiyContext.fsGroup`: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

https://github.com/kubernetes-csi/csi-driver-nfs/blob/c0384021447340d2a5bf2c8cb65e47addcf6c682/deploy/csi-nfs-driverinfo.yaml#L11

**Comment by andyzhangx** [comment]
btw, this driver set mountPermission here:  https://github.com/kubernetes-csi/csi-driver-nfs/blob/c0384021447340d2a5bf2c8cb65e47addcf6c682/pkg/nfs/nodeserver.go#L117-L118
not sure whether there is a quick fix to set gid, uid if `mountPermission` is set as `2770`, the `0` in `0770` means Octal, is `2770` valid?

**Comment by Elegant996** [comment]
The permissions do not appear to work as an Octal if it is applied as an argument (`--mount-permissions=2770`). The permissions become rather strange...

We opted to use the `master` branch so that we may try `mountPermissions` as a `StorageClass` parameter and the sticky bit appears to be flat out ignored in that secenario.

**Comment by Elegant996** [comment]
`fsGroupPolicy: File` enables `setgid` on the mount but the same should be achievable through `fsGroupPolicy: None` and then adding the sticky bit by hand. This has broughten up another issue though. Will file it separately.

**Comment by andyzhangx** [comment]
o, recently I realized that we should set `fsGroupPolicy` as `ReadWriteOnceWithFSType` by default, for NFS, I don't think we should set group id recursively on the volume mount:

https://github.com/kubernetes-csi/csi-driver-nfs/blob/e9ceb486bc6f307b7e54c96b137e8a55f8d0cd62/deploy/csi-nfs-driverinfo.yaml#L11

**Comment by andyzhangx** [comment]
you could now set `mountPermissions=0` in storage class parameters to skip chmod with master branch image (`gcr.io/k8s-staging-sig-storage/nfsplugin:canary`):  
https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/docs/driver-parameters.md#storage-class-usage-dynamic-provisioning

**Comment by Elegant996** [comment]
Opted for a combination of setting the `--mount-permissions=0` (since most of our mounts use ACLs) and changing to `fsGroupPolicy: ReadWriteOnceWithFSType`.  We will specify the permissions of those that are not manually which should simplify everything.

**Comment by andyzhangx** [comment]
> Opted for a combination of setting the `--mount-permissions=0` (since most of our mounts use ACLs) and changing to `fsGroupPolicy: ReadWriteOnceWithFSType`. We will specify the permissions of those that are not manually which should simplify everything.
> 
> Thanks!

@Elegant996 I am still stuggling whether we should set `fsGroupPolicy: ReadWriteOnceWithFSType` by default for this nfs csi driver, it's now `fsGroupPolicy: File` by default.  @gnufied do you have any guidance on this?
