### ISSUE TITLE
Enable k8s e2e tests in CI

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/csi-driver-nfs#33]
Once CreateVolume is supported, then it will be easier to run the K8s external storage e2e test suite.

One more challenge though is getting the nfs driver to run on a kind cluster. There may be some dependencies on kernel modules or system libraries.

**Comment by BenTheElder** [comment]
cc

We need `nfs-common` right?
When we started kind lots of kernels couldn't do NFS-on-overlayfs IIRC you need 4.15+ but that's very common now..

I'm, looking at increasing e2e test coverage this quarter, NFS is a target on my list.

**Comment by BenTheElder** [comment]
`nfs-common` is in the latest base image, and the k/k `\[Driver:.nfs\]` (excluding `\[Disruptive\]` tests pass

**Comment by andyzhangx** [comment]
basic e2e tests are added in CI
