### ISSUE TITLE
Wrong node selector for runOnMaster=true value of helm chart

### ISSUE THREAD

**Issue by Eshva** [kubernetes-csi/csi-driver-nfs#344]
**What happened**:
If one uses value `runOnMaster: true` of helm chart the result `csi-nfs-controller` pods have wrong node selector:
```
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/role: master
```
...and can't be scheduled due lack of such nodes.

The problem in `kubernetes.io/role: master`. Master nodes (at least on Kubernetes 1.23) have no such label:
```
Name:               master01
Roles:              control-plane,master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=master01
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/control-plane=
                    node-role.kubernetes.io/master=
                    node.kubernetes.io/exclude-from-external-load-balancers=
Annotations:        csi.volume.kubernetes.io/nodeid: {"nfs.csi.k8s.io":"master01"}
                    kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/containerd/containerd.sock
                    node.alpha.kubernetes.io/ttl: 0
                    projectcalico.org/IPv4Address: 10.23.23.11/24
                    projectcalico.org/IPv4VXLANTunnelAddr: 192.168.160.0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
```
...but of course have corresponding role.

**What you expected to happen**:
I see only 2 possibilities (I'm not a profi in Kubernetes, may be there are more solutions):
1. Find a way to select nodes by it's roles.
2. Document this case and require user to place label `kubernetes.io/role: master` on each master node.

**How to reproduce it**:
Install NFS CSI driver using helm chart with value `runOnMaster` set to true:
```
helm install csi-driver-nfs csi-driver-nfs/csi-driver-nfs --namespace kube-system --version v4.0.0 --set runOnMaster=true
```

Get all pods in namespace `kube-system`:
```
kubectl get pod --namespace kube-system
```

You'll see all the `csi-nfs-controller` pods are pending:
```
NAME                                  READY   STATUS    RESTARTS        AGE
coredns-64897985d-nfhcc               1/1     Running   8 (6d3h ago)    28d
coredns-64897985d-swfgs               1/1     Running   8 (6d3h ago)    28d
csi-nfs-controller-789bbcc876-2vwgp   3/3     Pending   0               127m
csi-nfs-controller-789bbcc876-69rn9   3/3     Pending   0               127m
csi-nfs-node-5dvjj                    3/3     Running   0               127m
csi-nfs-node-88kxd                    3/3     Running   0               127m
```

Describe some of `csi-nfs-controller` pod and notice in Events section that pod is not scheduled due wrong affinity or node selectors.

Describe a master node and notice in Labels section lack of a label `kubernetes.io/role: master`.

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: 4.0.0 and 4.1.0
- Kubernetes version (use `kubectl version`): v1.23.6
- OS (e.g. from /etc/os-release): Debian GNU/Linux 11 (bullseye)
- Kernel (e.g. `uname -a`): Linux master01 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
- Install tools: Helm
- Others:

**Comment by andyzhangx** [comment]
let me change to matching `node-role.kubernetes.io/master: ""` with a new PR, thanks for pointing out.
