### ISSUE TITLE
deploy/uninstall-driver.sh can't clean rbac 

### ISSUE THREAD

**Issue by huanghantao** [kubernetes-csi/csi-driver-nfs#351]
**What happened**:

```bash
./uninstall-driver.sh v3.1.0
Uninstalling NFS driver, version: v3.1.0 ...
deployment.apps "csi-nfs-controller" deleted
daemonset.apps "csi-nfs-node" deleted
csidriver.storage.k8s.io "nfs.csi.k8s.io" deleted
error: unable to read URL "https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v3.1.0/deploy/v3.1.0/rbac-csi-nfs.yaml", server reported 404 Not Found, status code=404
```

**What you expected to happen**:

clean old version rbac

**Anything else we need to know?**:

A similar problem occurs during installation and uninstallation. The script in the master branch was changed.

**Comment by andyzhangx** [comment]
pls run following command to clean up v3.1.0 deployments:
```console
git checkout v3.1.0 
./deploy/uninstall-driver.sh v3.1.0 local
```

**Comment by andyzhangx** [comment]
btw, actually you could run `./deploy/uninstall-driver.sh v4.0.0 local` to clean up deployments, there is not much difference.
