### ISSUE TITLE
csi-driver-nfs stops working and can't provision after microk8s node restart

### ISSUE THREAD

**Issue by yingding** [kubernetes-csi/csi-driver-nfs#354]
**What happened**:
I have a 3 nodes microk8s cluster, and works fine with v4.1.0 helm3 charts of csi-driver-nfs. I installed the csi-driver-nfs following the instruction from https://microk8s.io/docs/nfs, after i restarted two worker nodes of microk8s, the csi-driver-nfs stops working. There is no error in the logs of csi-driver-nfs controller and nodes

**What you expected to happen**:
After the microk8s worker nodes restart, the csi-driver-nfs shall function further

**How to reproduce it**:
1. make a microk8s cluster with 3 nodes
2. deploy the csi-driver-nfs with helm3 chart v4.1.0, and connect successfully to a nfs export
3. restart two nodes of microk8s cluster
4. Wait for the two microk8s nodes restarted successfully and the csi-driver-nfs controller and node pods also restarted successfully
5. try to use a pvc to provision a new pv 

**Anything else we need to know?**:
I found the work arround is to delete the helm3 csi-driver-nfs chart and redeploy the helm3 chart with the instruction from https://microk8s.io/docs/nfs. 

I also tried to restart all the pod with `kubectl delete pod --selector app.kubernetes.io/name=csi-driver-nfs --namespace kube-system`, and it doesn't work.

There was no error in the logs:
```
microk8s kubectl logs --selector app=csi-nfs-controller -n kube-system -c nfs
microk8s kubectl logs --selector app=csi-nfs-node -n kube-system -c nfs
```

**Environment**:
- CSI Driver version: 4.1.0
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-17T22:28:26Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.12-3+6937f71915b56b", GitCommit:"6937f71915b56b6004162b7c7b3f11f196100d44", GitTreeState:"clean", BuildDate:"2022-04-28T11:11:24Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from /etc/os-release): NAME="Ubuntu" VERSION="20.04.3 LTS (Focal Fossa)"
- Kernel (e.g. `uname -a`): Linux 5.4.0-120-generic Ubuntu SMP Fri Jun 10 13:40:48 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: snap, microk8s
- Others:

**Comment by andyzhangx** [comment]
if `csi-nfs-controller` is running on one worker node which is restarting, the `csi-nfs-controller` would not accept any request, so that's by design.

**Comment by andyzhangx** [comment]
@yingding not sure, I think you should get `kubectl logs csi-nfs-controller-56bfddd689-dh5tk -c nfs -n kube-system -c csi-provisioner` to take a look if there is any PVC provision.

**Comment by yingding** [comment]
@andyzhangx Thanks, next time wenn i run into this issue. I will try `kubectl logs csi-nfs-controller-56bfddd689-dh5tk -c nfs -n kube-system -c csi-provisioner` to see if `-c csi-provisioner` option gives me further log infos.

**Comment by yingding** [comment]
ok. I fall back to helm3 chart v4.0.0 and every thing works now. It is an issue of v4.1.0.

**Comment by andyzhangx** [comment]
I will try release v4.1.0 version late this week.

**Comment by yingding** [comment]
Thanks, I thought initially I have to use v4.1.0 since it supports 1.20+ and my k8s is 1.21.12
