### ISSUE TITLE
Simplify the example

### ISSUE THREAD

**Issue by ensonic** [kubernetes-csi/csi-driver-nfs#38]
hi,
if I am not mistaken we don't need the label + selector in the example:
https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/examples/kubernetes/nginx.yaml#L5-L6
https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/examples/kubernetes/nginx.yaml#L29-L33

I am hesitant to sent a PR because I still did not got it to run on my kubeadm setup (1.16)

**Comment by wozniakjan** [comment]
hi @ensonic, you are correct that whenever you have a single unbound PV in cluster, the label selector doesn't play a big role. The situation changes slightly when there are couple of PVs provisioned for different storage. [The selector tries to ensure](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector) that the PVC won't get bound to any other storage matching the base requirements (storage type, size, ...) but this concrete NFS CSI plugin provisioned PV.

**Comment by msau42** [comment]
In the scenario that you want to reserve a PV for a specific PVC, it is recommended to set PV.Spec.ClaimRef instead of a selector.

**Comment by ensonic** [comment]
There are not many example for people using a ClaimRef and it seems to be not super straightforward to use (https://github.com/kubernetes/kubernetes/issues/23615).
Anyway, since the selector works, I think we can close this.
