### ISSUE TITLE
How to debug timeout after 2 min for trying to attach the volume

### ISSUE THREAD

**Issue by ensonic** [kubernetes-csi/csi-driver-nfs#39]
Since the nfs example in
https://github.com/kubernetes/examples/tree/master/staging/volumes/nfs
fails to resolve an in-cluster nfs server I was directed to try CSI based nfs and here I am. So I added the yaml from
https://github.com/kubernetes-csi/csi-driver-nfs/tree/master/deploy/kubernetes
without any modification to my helm chart. The pv/pvc look like this to let me switch back and forth:
``` yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
{{- if .Values.use_csi }}
  csi:
    driver: nfs.csi.k8s.io
    # seems to be unused if volume is only used once
    volumeHandle: data
    volumeAttributes:
      server: nfs-server.app-data.svc.cluster.local
      share: /exports
{{- else }}
  nfs:
    path: /exports
    server: nfs-server.app-data.svc.cluster.local
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi
```
The whole chart gets installed to a namespace `app-data` by helm. The nfs-server comes up, the csi plugin comes up. The pv and pvc come up as bound, but the pods never come up :/ After ~2 minutes I get the error below and that keeps repeating:
```
Events:
  Type     Reason              Age    From                                       Message
  ----     ------              ----   ----                                       -------
  Normal   Scheduled           2m32s  default-scheduler                          Successfully assigned app-data/data-reader-bmv5z to master.local
  Warning  FailedAttachVolume  32s    attachdetach-controller                    AttachVolume.Attach failed for volume "data" : attachment timeout for volume data
  Warning  FailedMount         29s    kubelet, master.local  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[default-token-r2q5v data]: timed out waiting for the condition
  Warning  FailedAttachVolume  0s     attachdetach-controller                    AttachVolume.FindAttachablePluginBySpec failed for volume "data"
```

Looks like this
https://github.com/kubernetes/kubernetes/issues/89173

Nothing in the logs of the csi plugin though. The cluster is a 2 node kubeadm cluster (1.16).

Any idea whats going on?

**Comment by msau42** [comment]
If you created the PVC/PV before starting the CSI driver, you may be hitting the issue above.

Can you try recreating the Pod and PVC/PV?

**Comment by ensonic** [comment]
Its indeed the ordering, but now I bump into the same problem as with the in-tree nfs:
```
MountVolume.SetUp failed for volume "data" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Internal desc = mount failed: exit status 32
    Mounting command: mount
    Mounting arguments: -t nfs nfs-server.app-data.svc.cluster.local:/exports /var/lib/kubelet/pods/93e33295-23bb-43a7-96ce-aac12161ca2e/volumes/kubernetes.io~csi/data/mount
    Output: mount.nfs: Failed to resolve server nfs-server.app-data.svc.cluster.local: Name or service not known
```

**Comment by ensonic** [comment]
I've split my helm chart into two. One to create the csi plugin (everything from https://github.com/kubernetes-csi/csi-driver-nfs/tree/master/deploy/kubernetes + the nfs server) and a 2nd one to deploy a set of clients + pv + pvc and that kind of works, except that also the csi plugin cannot resolve an in cluster service name (nfs-server.nfs-server.svc.cluster.local).

Will check how the csi plugin works and how it does the mount. maybe it could attempt to resolve the name first before building the mount command-line? Like here:
https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/pkg/nfs/nodeserver.go#L61
inside the k8s mount utils this is probably too late:
https://github.com/kubernetes-csi/csi-driver-nfs/blob/1bb6a868c144a2cfad2872f47a0789e159ad4535/vendor/k8s.io/kubernetes/pkg/util/mount/exec_mount.go#L46

**Comment by msau42** [comment]
That's very odd. If you look at csi driver logs, how long does the NodePublishVolume call take?

**Comment by ensonic** [comment]
The daemonset has 2 containers: node-driver-registrar and nfs. Both don't log anything during the mount operation. The 'node-driver-registrar' already runs with `--v=5', but there is not a lot of logging in the code.
