### ISSUE TITLE
Create initial release of csi-driver-nfs

### ISSUE THREAD

**Issue by saad-ali** [kubernetes-csi/csi-driver-nfs#4]
1. Do some manual testing to ensure this NFS driver works as intended.
2. Create a `release-0.1` branch for kubernetes-csi/csi-driver-nfs
3. Cut an official release v0.1.0 release of this driver from the new branch.
4. Push a csi-driver-nfs:v0.1.0 container (either to quay or gcr.io whatever the Kubernetes CSI team decides)
  * Note that there is an existing container https://quay.io/repository/k8scsi/nfsplugin?tab=tags from the old repo (https://github.com/kubernetes-csi/drivers)

CC @prateekpandey14 @msau42

**Comment by msau42** [comment]
Before we do that, we should also:
- [ ] Use release-tools for common process
- [ ] Remove dependency on csi-lib-common

cc @pohly

**Comment by pohly** [comment]
I was about to suggest the same as @msau42.

One comment about branching: it is not necessary to start such a branch right away. The initial release can also be done from the master branch and then (if necessary) a maintenance branch can be created later.

**Comment by msau42** [comment]
In order to use csi-release-tools, we also need to switch to go mod too.
/help

**Comment by wozniakjan** [comment]
I can try to convert this to go modules over the weekend unless anyone else wants to take that sooner

**Comment by wozniakjan** [comment]
@msau42 do you have any more steps in mind before the `v1.0.0` release? Btw. I think the tag of the first release should actually be `v1.0.0` instead of here proposed `v0.1.0` given this string is in the manifests to pull the docker image and also in one location in code.

I am afraid my account isn't authorized to create the release itself so it may need to be you to perform the final steps.

**Comment by msau42** [comment]
Can we also address these two issues?
https://github.com/kubernetes-csi/csi-driver-nfs/issues/19
https://github.com/kubernetes-csi/csi-driver-nfs/issues/3

**Comment by msau42** [comment]
I will look into making sure travis and prow are setup on this repo

**Comment by wozniakjan** [comment]
> Can we also address these two issues?
> #19
> #3

sure thing, will do so by Monday

**Comment by msau42** [comment]
@wozniakjan one more issue I think should be done for the release: https://github.com/kubernetes-csi/csi-driver-nfs/issues/25

**Comment by msau42** [comment]
Also I just enabled prow pull jobs on this repo, and double checked travis and quay are setup to build and release images.

**Comment by msau42** [comment]
A 2.0.0 has been released! Thanks @wozniakjan for all the work in finishing up all the last mile tasks!

/close
