### ISSUE TITLE
RWO is supported and respected by csi-nfs

### ISSUE THREAD

**Issue by rbaumgar** [kubernetes-csi/csi-driver-nfs#403]
**What happened**:
I created a PVC with RWO access mode, and it can be used with two pods running on different nodes
**What you expected to happen**:
RWO PVCs should be mountable only by one pod!
RWO is used intentionally to protect the volume. It should not be possible to mount it twice!
**How to reproduce it**:
1. Created a PVC with RWO access mode.
2. Create a deployment with replicaset=2, the pod is using this PVC
**Anything else we need to know?**:
I am expecting that the first pod will start. Second pod should fail, because PVC can not be mounted.
**Environment**:
- CSI Driver version: 4.1.0
- Kubernetes version (use `kubectl version`): v1.25.4+77bec7a
- OS (e.g. from /etc/os-release): Red Hat Enterprise Linux CoreOS 8.6
- Kernel (e.g. `uname -a`): 4.18.0-372.40.1.el8_6.x86_64
- Install tools: ./deploy/install-driver.sh v4.1.0 local
- Others:
This is a duplicate https://github.com/kubernetes-csi/csi-driver-nfs/issues/384, but this has not been solved! Just closed.

**Comment by andyzhangx** [comment]
I think you are referring to `RWOP` https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

```
RWO - ReadWriteOnce
RWOP - ReadWriteOncePod
```

**Comment by andyzhangx** [comment]
but this feature is still in alpha state now, you need to enable this feature manually: https://kubernetes.io/blog/2021/09/13/read-write-once-pod-access-mode-alpha/

**Comment by rbaumgar** [comment]
NO, I mentioned RWO!

This is the definition:
_The ReadWriteOnce access mode **restricts volume access to a single node**, which means it is possible for multiple pods on the same node to read from and write to the same volume._

The pods are running on different nodes!!!
But it is good hint that RWOP will be available soon.

**Comment by andyzhangx** [comment]
accessModes do not enforce access right, but rather act as labels to match a PV to a PVC. One PV could only be bound to one PVC, and one PVC (after bound to a PV) could be used by multiple pods, and if pods are on different nodes, then that pvc would be used on multiple nodes.

**Comment by smd134** [comment]
Still not usable RWOP in aks?

**Comment by andyzhangx** [comment]
> RWOP

@smd134 yes, `RWOP` is an alpha feature, not available on aks now.

**Comment by rbaumgar** [comment]
@andyzhangx I don't know why you closed this issue.
RWO: 
_The ReadWriteOnce access mode **restricts volume access to a single node**, which means it is possible for multiple pods on the same node to read from and write to the same volume._

This means  - in my opinion - that I can't mount the same PV on different nodes. But this is possible!

**Comment by andyzhangx** [comment]
current accessMode is only for matching pv/pvc, it does not prevent two pods on two nodes to access same pvc. btw, this is not directly related to this driver, it's more like k8s upstream feature discussion.

**Comment by rbaumgar** [comment]
then at least it's a documentation bug!
