### ISSUE TITLE
helm lint fails

### ISSUE THREAD

**Issue by tyriis** [kubernetes-csi/csi-driver-nfs#404]
**What happened**:
When calling `helm lint csi-driver-nfs-v4.1.0.tgz` I got the following error:
```
==> Linting csi-driver-nfs-v4.1.0.tgz
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/rbac-csi-nfs.yaml: unable to parse YAML: invalid Yaml document separator: kind: ClusterRole

Error: 1 chart(s) linted, 1 chart(s) failed
```

**What you expected to happen**:
Linting should pass without errors.

**How to reproduce it**:
`helm pull csi-driver-nfs/csi-driver-nfs && helm lint csi-driver-nfs-v4.1.0.tgz`

**Anything else we need to know?**:
maybe related to: https://github.com/helm/helm/issues/10149

**Environment**:
```
helm version  
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.19.4"}
```

**Comment by tyriis** [comment]
have tested it a little bit, by changing the template to not eat up the line break, linting get fixed.

**Comment by tyriis** [comment]
I can open a pr but it looks pretty complicated. Should I add a v4.1.1 chart? or is this autogenerated at some point?

**Comment by andyzhangx** [comment]
it's fixed by https://github.com/kubernetes-csi/csi-driver-nfs/pull/393

**Comment by andyzhangx** [comment]
v4.1.0 should have the right format now

**Comment by tyriis** [comment]
did you just overwrite/ re-published the existing chart?

**Comment by tyriis** [comment]
@andyzhangx did you just overwrite/ re-published the existing chart?

**Comment by andyzhangx** [comment]
> @andyzhangx did you just overwrite/ re-published the existing chart?

@tyriis yes, could you update your chart repo?

**Comment by tyriis** [comment]
It is working now, but need to invalidate several caches. Better solution would be a semantic version increment :D

Thanks for your work, it solved a major issue for me.

**Comment by andyzhangx** [comment]
@tyriis that's a helm chart issue, so it's better fixing issue directly, thanks for the confirm.

**Comment by tyriis** [comment]
@andyzhangx there is a helm chart version and an application version for this. (but I am sure you know it, helm technology is somehow limited :D)
