### ISSUE TITLE
Node selector for control plane nodes is still wrong

### ISSUE THREAD

**Issue by evilhamsterman** [kubernetes-csi/csi-driver-nfs#407]
**What happened**:
Set `values.controller.runOnControlPlane` to `true` but the controller fails to deploy because the nodeSelector then gets set to 
```yaml
node-role.kubernetes.io/control-plane: ""
```
Which works for the person who reported #344 but some k8s distros such as K3S set the value to 
```yaml
node-role.kubernetes.io/control-plane: "true"
```

**What you expected to happen**:
The pods to deploy on the control plane nodes

**How to reproduce it**:
Deploy a k3s cluster with a control plane and worker nodes. Taint the control plane nodes with NoSchedule. Try to deploy the csi-driver-nfs using the settings above.

**Anything else we need to know?**:
Like the other guy if I ignore the runOnControlPlane and just add my own node selector it works fine. To avoid this it would probably be best to just skip the runOnControlPlane value and people can just add their own selectors if needed.

**Environment**:

- CSI Driver version: 4.1.0
- Kubernetes version (use `kubectl version`): v1.25.6+k3s1
- OS (e.g. from /etc/os-release): Ubuntu 22.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
I think you could just set `runOnControlPlane` as false to workaround this issue, and by default, it's false.

**Comment by evilhamsterman** [comment]
You can, and that's eventually what I did, but the documentation says just set this variable to true to have it run on control plane nodes. I deployed it and the pods could not be scheduled. I had to dig into the pods and the templates to realize what was going on.

Since different k8s distros use and have used different ways to label control-plane nodes it would probably be best to just leave it to the user to specify, or at least call out in the docs the nodeSelector.
