### ISSUE TITLE
New Release Request

### ISSUE THREAD

**Issue by alankan-finocomp** [kubernetes-csi/csi-driver-nfs#414]
Hi! I am following this guide https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/RELEASE.md to request a new release.

Changelog => compared commits:
https://github.com/kubernetes-csi/csi-driver-nfs/compare/v4.1.0...master

I have eyeball-checked a bit and these commits consist of chores, fixes, and introducing some new Helm chart values. Will that be a minor version then I guess? i.e. 4.2.0

Thank you very much in advance for looking into this request :pray:

**Comment by andyzhangx** [comment]
there is already a PR: https://github.com/kubernetes-csi/csi-driver-nfs/pull/401, let me rework on that PR.

**Comment by andyzhangx** [comment]
wait a moment for this PR(https://github.com/kubernetes-csi/csi-driver-nfs/pull/415) get merged first, and then I will cut a new release

**Comment by andyzhangx** [comment]
`docker pull registry.k8s.io/sig-storage/nfsplugin:v4.2.0`
