### ISSUE TITLE
registry.k8s.io/sig-storage/nfsplugin:v4.2.0 referenced in chart but not available

### ISSUE THREAD

**Issue by tyriis** [kubernetes-csi/csi-driver-nfs#418]
**What happened**:
I installed the latest chart v4.2.0 and I got this:

```
NAME↑                     PF    IMAGE                                                            READY     STATE
liveness-probe            ●     registry.k8s.io/sig-storage/livenessprobe:v2.8.0                 true      Running
nfs                       ●     registry.k8s.io/sig-storage/nfsplugin:v4.2.0                     false     ImagePullBackOff
node-driver-registrar     ●     registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.6.2     true      Running
```

The referenced image `registry.k8s.io/sig-storage/nfsplugin:v4.2.0` is not present :cry: 

**What you expected to happen**:

I expect the image to be present :sweat_smile: 

**How to reproduce it**:

```console
➜ docker pull registry.k8s.io/sig-storage/nfsplugin:v4.2.0
Error response from daemon: manifest for registry.k8s.io/sig-storage/nfsplugin:v4.2.0 not found: manifest unknown: Failed to fetch "v4.2.0"
```

**Anything else we need to know?**:

...

**Environment**:
not an environment issue if image does not exist

**Comment by andyzhangx** [comment]
it depends on https://github.com/kubernetes/k8s.io/pull/4805 for image publishing

**Comment by tyriis** [comment]
@andyzhangx okay, but then you should not release a chart pointing to an non existing image.

**Comment by rykelley** [comment]
Same problem. Please publish updated image

**Comment by addich** [comment]
in the meantime the images are there. please try again

**Comment by andyzhangx** [comment]
`docker pull registry.k8s.io/sig-storage/nfsplugin:v4.2.0` is published, sorry for the delay, I will make the image publish process faster next time.
