### ISSUE TITLE
how to really manage  the capacity of pv pvc when use nfs as kubernetes storage ? 

### ISSUE THREAD

**Issue by linpanru** [kubernetes-csi/csi-driver-nfs#427]
when user nfs as k8s storage, sometime ,I apply a 1G pvc ,but i can write more than 1G data to this pvc ,  so how can i really manage or restrict the capacity of nfs pv pvc ?

**Comment by andyzhangx** [comment]
the capacity of nfs pv pvc is only for pv/pvc matching, there is no way to restrict the actual capacity in k8s now, this is not this csi driver issue.

**Comment by linpanru** [comment]
> the capacity of nfs pv pvc is only for pv/pvc matching, there is no way to restrict the actual capacity in k8s now, this is not this csi driver issue.

Is it necessary for nfs to really support true capacity management in the first ,then csi driver can manage the capacity of pv/pvc?

**Comment by wozniakjan** [comment]
> Is it necessary for nfs to really support true capacity management in the first

afaik, NFS kind of supports per UID/GID disk quota, but it's not usable in the context of CSI driver and NFS protocol itself has no support for clients to communicate desired quotas, it would have to be configured serverside.

**Comment by linpanru** [comment]
> > Is it necessary for nfs to really support true capacity management in the first
> 
> afaik, NFS kind of supports per UID/GID disk quota, but it's not usable in the context of CSI driver and NFS protocol itself has no support for clients to communicate desired quotas, it would have to be configured serverside.

thanks for your explanation，and if I use ceph storage as k8s storage , can i really manage the capacity of pv/pvc by cephcsi plugin?

**Comment by wozniakjan** [comment]
> thanks for your explanation，and if I use ceph storage as k8s storage , can i really manage the capacity of pv/pvc by cephcsi plugin?

I have limited knowledge of ceph, I would recommend consulting docs https://docs.ceph.com/ or reaching out to ceph community on github (https://github.com/ceph/ceph-csi) or slack (https://cephcsi.slack.com/). It also will likely depend on the protocol, ceph supports rdb, fuse, nfs, and they all will likely have tradeoffs and limitations.

**Comment by andyzhangx** [comment]
> > > Is it necessary for nfs to really support true capacity management in the first
> > 
> > 
> > afaik, NFS kind of supports per UID/GID disk quota, but it's not usable in the context of CSI driver and NFS protocol itself has no support for clients to communicate desired quotas, it would have to be configured serverside.
> 
> thanks for your explanation，and if I use ceph storage as k8s storage , can i really manage the capacity of pv/pvc by cephcsi plugin?

@linpanru as I said, k8s pv/pvc won't enforce capacity management, the capacity in pv/pvc is only for matching purpose. while if you create a fixed size in ceph, it may prevent you writing data size bigger than that size, while that depends on the underlying storage you are using.

**Comment by linpanru** [comment]
> > thanks for your explanation，and if I use ceph storage as k8s storage , can i really manage the capacity of pv/pvc by cephcsi plugin?
> 
> I have limited knowledge of ceph, I would recommend consulting docs https://docs.ceph.com/ or reaching out to ceph community on github (https://github.com/ceph/ceph-csi) or slack (https://cephcsi.slack.com/). It also will likely depend on the protocol, ceph supports rdb, fuse, nfs, and they all will likely have tradeoffs and limitations.

thanks for your help very much ! 

> > > > Is it necessary for nfs to really support true capacity management in the first
> > > 
> > > 
> > > afaik, NFS kind of supports per UID/GID disk quota, but it's not usable in the context of CSI driver and NFS protocol itself has no support for clients to communicate desired quotas, it would have to be configured serverside.
> > 
> > 
> > thanks for your explanation，and if I use ceph storage as k8s storage , can i really manage the capacity of pv/pvc by cephcsi plugin?
> 
> @linpanru as I said, k8s pv/pvc won't enforce capacity management, the capacity in pv/pvc is only for matching purpose. while if you create a fixed size in ceph, it may prevent you writing data size bigger than that size, while that depends on the underlying storage you are using.

thanks for your help very much .

**Comment by linpanru** [comment]
> > thanks for your explanation，and if I use ceph storage as k8s storage , can i really manage the capacity of pv/pvc by cephcsi plugin?
> 
> I have limited knowledge of ceph, I would recommend consulting docs https://docs.ceph.com/ or reaching out to ceph community on github (https://github.com/ceph/ceph-csi) or slack (https://cephcsi.slack.com/). It also will likely depend on the protocol, ceph supports rdb, fuse, nfs, and they all will likely have tradeoffs and limitations.

thanks for your help very much !
