### ISSUE TITLE
Multiple PVC failed mount on single Pod in NFS static Provisioning

### ISSUE THREAD

**Issue by Nagarajan0396** [kubernetes-csi/csi-driver-nfs#428]
Pod status Container creating state.
**Error:**
Warning  FailedMount  8m12s                kubelet            Unable to attach or mount volumes: unmounted volumes=[staticfiles], unattached volumes=[app-config kube-api-access-8vltf staticfiles media]: timed out waiting for the condition

I installed this nfs-csi-driver: https://github.com/kubernetes-csi/csi-driver-nfs/tree/master/charts/v4.2.0/csi-driver-nfs

then, I deployed 

**nfs-server.yaml** 
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-server
  labels:
    app: nfs-server
spec:
  type: ClusterIP  # use "LoadBalancer" to get a public ip
  selector:
    app: nfs-server
  ports:
    - name: tcp-2049
      port: 2049
      protocol: TCP
    - name: udp-111
      port: 111
      protocol: UDP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      name: nfs-server
      labels:
        app: nfs-server
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: nfs-server
          image: itsthenetwork/nfs-server-alpine:latest
          env:
            - name: SHARED_DIRECTORY
              value: "/exports"
          volumeMounts:
            - mountPath: /exports
              name: nfs-vol
          securityContext:
            privileged: true
          ports:
            - name: tcp-2049
              containerPort: 2049
              protocol: TCP
            - name: udp-111
              containerPort: 111
              protocol: UDP
      volumes:
        - name: nfs-vol
          hostPath:
            path: /nfs-vol  # modify this to specify another path to store nfs share data
            type: DirectoryOrCreate
            
 **storageclass-nfs.yaml**
 ---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: <nfs-server-ip>
  share: /
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1   
  
**pv-nfs-csi.yaml**
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: pv-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: <nfs-server-ip>
    volumeAttributes:
      server: <nfs-server-ip>
      share: /
         
 **pvc-nfs-static.yaml**
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: divy-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeName: pv-nfs
  storageClassName: nfs-csi
  
**pv-nfs.yaml**
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: pv-nfs-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: <nfs-server-ip>
    volumeAttributes:
      server: <nfs-server-ip>
      share: /

**pvc-nfs-static.yaml** 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: divy-staticfiles
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeName: pv-nfs-1
  storageClassName: nfs-csi
  
  **pod.yaml**
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: staticfiles
      mountPath: /app/staticfiles
    - name: media
      mountPath: /app/media
  volumes:
  - name: staticfiles
    persistentVolumeClaim:
      claimName: divy-staticfiles
  - name: media
    persistentVolumeClaim:
      claimName: divy-media
      
 Environment: AWS-EKS CLUSTER
 Kubernetes Version: 1.24
 Node Kernel Version: 5.10.165-143.735.amzn2.x86_64
 OS Image: Amazon Linux 2
 
 @andyzhangx  Can u please give the solution for this Error.
 
 **NOTE:** I'm trying files sharing across the namespaces.###

**Comment by andyzhangx** [comment]
what's the mount error logs on the node? https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/docs/csi-debug.md#case2-volume-mountunmount-failed

**Comment by Nagarajan0396** [comment]
there is no error logs.

**Comment by Nagarajan0396** [comment]
this is my pod events which is had multiple pv and pvc 
![image](https://user-images.githubusercontent.com/105700660/225644987-4050ee2e-fd3c-46c4-9c59-48efedf02e78.png)

**Comment by andyzhangx** [comment]
pls type `-c nfs` in `kubectl logs ...` command, it's obviously not showing nfs driver logs

**Comment by Nagarajan0396** [comment]
![Screenshot from 2023-03-17 09-48-38](https://user-images.githubusercontent.com/105700660/225814082-730a31d1-3040-47b9-bc0d-970b792cfe6f.png)

**Comment by Nagarajan0396** [comment]
the pod is connected with first pv(name: pv-nfs) then next pv cant mount. that's why pod is container creating state.

**Comment by andyzhangx** [comment]
@Nagarajan0396 different PV could not share same `volumeHandle` value
