### ISSUE TITLE
Why not write mount information to /etc/fstab

### ISSUE THREAD

**Issue by Wang-Kai** [kubernetes-csi/csi-driver-nfs#431]
I read the code of csi-driver-nfs project, and the `NodePublishVolume` function does not write mount information after executing the mount operation.

Why the driver agent don’t do it ? I want to learn about the design logic of it.

**Comment by andyzhangx** [comment]
why would the csi driver write mount info to /etc/fstab? what's the benefit of this? the mount would be still valid after reboot? but if node is reboot, the k8s workloads should be moved to other nodes.

**Comment by Wang-Kai** [comment]
Thanks for your answer, i got it .
