### ISSUE TITLE
Failed install with helm chart v4.3.0

### ISSUE THREAD

**Issue by rabbagliettiandrea** [kubernetes-csi/csi-driver-nfs#456]
**What happened**:
`  Error: Failed to render chart: exit status 1: Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "volumesnapshots.snapshot.storage.k8s.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "csi-driver-nfs"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system`
**What you expected to happen**:
Installation OK

**How to reproduce it**:
helm install --version 4.3.0

**Anything else we need to know?**:

**Environment**:

- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rabbagliettiandrea** [comment]
I've just discovered that v.4.3.0 clashes with CRD defined by https://artifacthub.io/packages/helm/piraeus-charts/snapshot-controller 

Is it a bug in your opinion?

**Comment by rabbagliettiandrea** [comment]
If you put this in values.yaml all works:

```
externalSnapshotter:
  enabled: false
```

**Comment by tyriis** [comment]
Would be great to not have breaking changes in minor chart versions :slightly_smiling_face:, for me renovate is picking up new minor releases.
