### ISSUE TITLE
registry.k8s.io/sig-storage/nfsplugin:v4.3.0 referenced in chart but not available

### ISSUE THREAD

**Issue by muhlba91** [kubernetes-csi/csi-driver-nfs#457]
**What happened**:

Similar to https://github.com/kubernetes-csi/csi-driver-nfs/issues/418 the image `registry.k8s.io/sig-storage/nfsplugin:v4.3.0` is referenced in the new `4.3.0` chart but image is not published yet.

I figured it depends on https://github.com/kubernetes/k8s.io/pull/5346.

Is it possible to couple these releases more tightly? At the moment, there's a pretty huge time difference, in my opinion.
In fact, updating the chart broke the deployment for one of my nodes (rolling updates enabled) due to this issue.

**What you expected to happen**:

The image being published when the chart is released.

**How to reproduce it**:

Install the `4.3.0` Helm chart.

**Comment by rabbagliettiandrea** [comment]
+1, same here

**Comment by nidr0x** [comment]
Same issue here.

**Comment by larivierec** [comment]
same issue here.

**Comment by andyzhangx** [comment]
registry.k8s.io/sig-storage/nfsplugin:v4.3.0 is published now
