### ISSUE TITLE
improve ut coverage

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/csi-driver-nfs#465]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

e.g. write a unit test for newNFSSnapshot func
https://github.com/kubernetes-csi/csi-driver-nfs/blob/862cb036e3f0d7c3fe28d2b127a6f96335b15309/pkg/nfs/controllerserver.go#L562

https://coveralls.io/github/kubernetes-csi/csi-driver-nfs?branch=master

![image](https://github.com/kubernetes-csi/csi-driver-nfs/assets/4178417/833051ab-a832-4282-a544-d5b217933cb3)

**Describe alternatives you've considered**

**Additional context**

**Comment by wozniakjan** [comment]
just providing some additional information about the current coverage for `newNFSSnapshot()` which is at 66%. While there is some coverage, especially the params section needs some extra love
https://github.com/kubernetes-csi/csi-driver-nfs/blob/862cb036e3f0d7c3fe28d2b127a6f96335b15309/pkg/nfs/controllerserver.go#L565-L574

to get more granular stats, the following code snippet can be used. Opening the `cover.html` in a browser gives a nice line-by-line view.
```
$ go test -covermode=count -coverpkg=./... -coverprofile cover.out -v ./pkg/nfs/...
$ go tool cover -html cover.out -o cover.html
$ go tool cover -func=cover.out | grep newNFSSnapshot
github.com/kubernetes-csi/csi-driver-nfs/pkg/nfs/controllerserver.go:562:       newNFSSnapshot                          66.7%
```
