### ISSUE TITLE
Allow csi-snapshotter to be enabled without installing CRDs

### ISSUE THREAD

**Issue by gclawes** [kubernetes-csi/csi-driver-nfs#467]
**Is your feature request related to a problem?/Why is this needed**
Currently, to enable the `csi-snapshotter` container in the controller Deployment, you must set `.Values.externalSnapshotter.enabled=true`.  This also causes the CRDs and snapshot-controller to be installed.  This causes a conflict if the underlying kubernetes distro also installs the CRDs and snapshot-controller

**Describe the solution you'd like in detail**
Either fully decouple the `csi-snapshotter` container from the installation of CRDs/snapshot-controller, or add an override value so this can be enabled without adding CRDs/snapshot-controller

**Describe alternatives you've considered**
See 2 options above.

**Comment by wozniakjan** [comment]
good point, the enablement was implemented to mimic how it's done in [azure CSI driver](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/8b37cd361590a79f23239cc2fb74f90cf58bd667/charts/latest/azurefile-csi-driver/values.yaml#L131-L155) but introducing fine-grained control over what gets installed should be a pure benefit.

**Comment by andyzhangx** [comment]
yes, we should set two different feature gate for nfs-controller and snapshot-controller.

**Comment by navilg** [comment]
Yes. This is causing the issue if crd is already present in cluster.

**Comment by navilg** [comment]
@gclawes I have updated the chart and tested on my cluster. You may also test this chart on your cluster.
Raised a PR.
