### ISSUE TITLE
Controller pod not created when installing in namespace other than kube-system namespace

### ISSUE THREAD

**Issue by navilg** [kubernetes-csi/csi-driver-nfs#477]
**What happened**:
csi-driver-nfs is working fine when I deploy it in kube-system namespace. It creates a controller pod and remaining daemonset pods. 
But when I deploy this in any other namespace, say, 'csi-driver-nfs' namespace, It only creates daemonset pods and no controller pod is created.

**What you expected to happen**:
Even in other namespaces, controller pod should have been created.

**How to reproduce it**:
Run below command to install cs-driver-nfs in other namespace

```
helm install csi-driver-nfs csi-driver-nfs/csi-driver-nfs --namespace csi-driver-nfs --version v4.2.0 --create-namespace
```

**Anything else we need to know?**:

**Environment**:

- CSI Driver version: v2.6.2
- Kubernetes version (use `kubectl version`): 1.24
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
@navilg it works on my machine:
```
# helm install csi-driver-nfs csi-driver-nfs/csi-driver-nfs --namespace csi-driver-nfs --version v4.2.0 --create-namespace
NAME: csi-driver-nfs
LAST DEPLOYED: Sun Jul 16 01:59:32 2023
NAMESPACE: csi-driver-nfs
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
The CSI NFS Driver is getting deployed to your cluster.

To check CSI NFS Driver pods status, please run:

  kubectl --namespace=csi-driver-nfs get pods --selector="app.kubernetes.io/instance=csi-driver-nfs" --watch
# k get all -n csi-driver-nfs
NAME                                      READY   STATUS    RESTARTS   AGE
pod/csi-nfs-controller-6f6c9b5748-2pgnh   3/3     Running   0          8s
pod/csi-nfs-node-4vxnm                    3/3     Running   0          8s
pod/csi-nfs-node-nblcz                    3/3     Running   0          8s

NAME                          DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
daemonset.apps/csi-nfs-node   2         2         2       2            2           kubernetes.io/os=linux   8s

NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/csi-nfs-controller   1/1     1            1           8s

NAME                                            DESIRED   CURRENT   READY   AGE
replicaset.apps/csi-nfs-controller-6f6c9b5748   1         1         1       8s
```

**Comment by navilg** [comment]
@andyzhangx Any possible reason it is not working on my machine ? I am using GKE cluster 1.24.

We are back to  "It works on my machine" problem :smiley:

**Comment by navilg** [comment]
Tried it on another cluster (Not GKE). It works fine there. Will update here if I find the root cause of not working on my GKE cluster.
