### ISSUE TITLE
Failing to mount volumes

### ISSUE THREAD

**Issue by MegaShinySnivy** [kubernetes-csi/csi-driver-nfs#479]
**What happened**:
I've noticed that on certain pods, mainly those that are using a RWX PVC provisioned by the driver being mounted on multiple pods, some pods take an extremely long time (over 24 minutes) to mount the volume. Manually mounting the NFS share on the node works just fine. This leads to pods getting stuck in terminating and creating, among other things.
**What you expected to happen**:
PVs are mounted in a timely manner. 
**How to reproduce it**:
Using TrueNAS, set up a basic NFS server using RAIDz2 and spinning disks. Install the driver and make a storageclass as per these values (https://github.com/MegaShinySnivy/flux-cluster/blob/main/kubernetes/apps/kube-system/csi-driver-nfs/app/storageclass.yaml and https://github.com/MegaShinySnivy/flux-cluster/blob/main/kubernetes/apps/kube-system/csi-driver-nfs/app/helmrelease.yaml), and start provisioning volumes.
**Anything else we need to know?**:
Inspecting the logs from the node the pod is running on, it seems the mount goes OK.
**Environment**: 

- CSI Driver version: v4.4.0
- Kubernetes version (use `kubectl version`): v1.27.3+k3s1
- OS (e.g. from /etc/os-release): Ubuntu 20.04.6 LTS
- Kernel (e.g. `uname -a`): 5.4.0-153-generic
- Install tools: Helm via Flux
- Others: Attached are descriptions and logs from the node. This happens on all nodes, though, not just this one.

[csi-nfs-node-description.log](https://github.com/kubernetes-csi/csi-driver-nfs/files/11994489/csi-nfs-node-description.log)
[csi-nfs-node.log](https://github.com/kubernetes-csi/csi-driver-nfs/files/11994490/csi-nfs-node.log)

**Comment by andyzhangx** [comment]
per the below logs, the mount only takes 0.1s, are you doing other operations after mount, .e.g. chown?

```
I0708 08:11:33.599998       1 utils.go:106] GRPC call: /csi.v1.Node/NodePublishVolume
I0708 08:11:33.600025       1 utils.go:107] GRPC request: {"target_path":"/var/lib/kubelet/pods/3754330e-5b79-4e7c-92c7-2dee89b468c7/volumes/kubernetes.io~csi/pvc-f335bae4-74cf-451c-b8a8-50e22704ffec/mount","volume_capability":{"AccessType":{"Mount":{"mount_flags":["nfsvers=3","hard","noatime","rw","user","nolock"]}},"access_mode":{"mode":5}},"volume_context":{"csi.storage.k8s.io/pv/name":"pvc-f335bae4-74cf-451c-b8a8-50e22704ffec","csi.storage.k8s.io/pvc/name":"sonarr-anime","csi.storage.k8s.io/pvc/namespace":"default","server":"10.0.30.12","share":"/mnt/THICCBOI1/K8s-NFS/","storage.kubernetes.io/csiProvisionerIdentity":"1688070772235-2499-nfs.csi.k8s.io","subDir":"default-sonarr-anime-pvc-f335bae4-74cf-451c-b8a8-50e22704ffec"},"volume_id":"10.0.30.12#mnt/THICCBOI1/K8s-NFS#default-sonarr-anime-pvc-f335bae4-74cf-451c-b8a8-50e22704ffec#pvc-f335bae4-74cf-451c-b8a8-50e22704ffec#"}
I0708 08:11:33.600307       1 nodeserver.go:123] NodePublishVolume: volumeID(10.0.30.12#mnt/THICCBOI1/K8s-NFS#default-sonarr-anime-pvc-f335bae4-74cf-451c-b8a8-50e22704ffec#pvc-f335bae4-74cf-451c-b8a8-50e22704ffec#) source(10.0.30.12:/mnt/THICCBOI1/K8s-NFS/default-sonarr-anime-pvc-f335bae4-74cf-451c-b8a8-50e22704ffec) targetPath(/var/lib/kubelet/pods/3754330e-5b79-4e7c-92c7-2dee89b468c7/volumes/kubernetes.io~csi/pvc-f335bae4-74cf-451c-b8a8-50e22704ffec/mount) mountflags([nfsvers=3 hard noatime rw user nolock])
I0708 08:11:33.600382       1 mount_linux.go:220] Mounting cmd (mount) with arguments (-t nfs -o nfsvers=3,hard,noatime,rw,user,nolock 10.0.30.12:/mnt/THICCBOI1/K8s-NFS/default-sonarr-anime-pvc-f335bae4-74cf-451c-b8a8-50e22704ffec /var/lib/kubelet/pods/3754330e-5b79-4e7c-92c7-2dee89b468c7/volumes/kubernetes.io~csi/pvc-f335bae4-74cf-451c-b8a8-50e22704ffec/mount)
I0708 08:11:33.601701       1 nodeserver.go:123] NodePublishVolume: volumeID(10.0.30.12#mnt/THICCBOI1/K8s-NFS#default-radarr-movies-pvc-5eb71599-6d4f-43bc-b98d-0fa7e673b430#pvc-5eb71599-6d4f-43bc-b98d-0fa7e673b430#) source(10.0.30.12:/mnt/THICCBOI1/K8s-NFS/default-radarr-movies-pvc-5eb71599-6d4f-43bc-b98d-0fa7e673b430) targetPath(/var/lib/kubelet/pods/3754330e-5b79-4e7c-92c7-2dee89b468c7/volumes/kubernetes.io~csi/pvc-5eb71599-6d4f-43bc-b98d-0fa7e673b430/mount) mountflags([nfsvers=3 hard noatime rw user nolock])
I0708 08:11:33.602028       1 mount_linux.go:220] Mounting cmd (mount) with arguments (-t nfs -o nfsvers=3,hard,noatime,rw,user,nolock 10.0.30.12:/mnt/THICCBOI1/K8s-NFS/default-radarr-movies-pvc-5eb71599-6d4f-43bc-b98d-0fa7e673b430 /var/lib/kubelet/pods/3754330e-5b79-4e7c-92c7-2dee89b468c7/volumes/kubernetes.io~csi/pvc-5eb71599-6d4f-43bc-b98d-0fa7e673b430/mount)
I0708 08:11:33.691003       1 nodeserver.go:140] skip chmod on targetPath(/var/lib/kubelet/pods/3754330e-5b79-4e7c-92c7-2dee89b468c7/volumes/kubernetes.io~csi/pvc-f335bae4-74cf-451c-b8a8-50e22704ffec/mount) since mountPermissions is set as 0
I0708 08:11:33.691059       1 nodeserver.go:142] volume(10.0.30.12#mnt/THICCBOI1/K8s-NFS#default-sonarr-anime-pvc-f335bae4-74cf-451c-b8a8-50e22704ffec#pvc-f335bae4-74cf-451c-b8a8-50e22704ffec#) mount 10.0.30.12:/mnt/THICCBOI1/K8s-NFS/default-sonarr-anime-pvc-f335bae4-74cf-451c-b8a8-50e22704ffec on /var/lib/kubelet/pods/3754330e-5b79-4e7c-92c7-2dee89b468c7/volumes/kubernetes.io~csi/pvc-f335bae4-74cf-451c-b8a8-50e22704ffec/mount succeeded
```

**Comment by MegaShinySnivy** [comment]
The only other op I would be doing is applying an FSPolicy, and from what I can see that applies successfully without issue.

**Comment by navilg** [comment]
@andyzhangx Same issue happening in our cluster with PVC of RWX type which have large amount of data (Around 500GB). 
When a pod is restarted, it fails with unable to attach or mount volumes error. And eventually get mounted after 3 to 4 hours.

I am running my workload on K8s 1.26 on GKE with containerd.

Below is the snippet of storageclass:

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
mountOptions:
- nfsvers=4.1
parameters:
  server: x.x.x.x
  share: /k8svol
provisioner: nfs.csi.k8s.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
```

@MegaShinySnivy is your issue fixed ? If yes, Would you able to share the fix

**Comment by andyzhangx** [comment]
@navilg 
follow this guide to set `securityContext.fsGroupChangePolicy: "OnRootMismatch"` 

https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods

**Comment by andyzhangx** [comment]
> is there a way to handle it at csi driver end ? I will need to patch this for every pods running on my cluster along with taking care of any future deployments

@navilg that's not possible since the kernel on the node does not have cifs driver installed.

**Comment by andyzhangx** [comment]
close this issue since cifs mount of the original issue actually succeeds.

**Comment by andyzhangx** [comment]
> is there a way to handle it at csi driver end ? I will need to patch this for every pods running on my cluster along with taking care of any future deployments

@navilg you could delete existing `CSIDriver` object, and create a new one with `fsGroupPolicy: None`, and then restart all pods, that could also workaround.

https://github.com/kubernetes-csi/csi-driver-nfs/blob/d84933dbd3c01e620fedfc49890a0e2c4113bd7e/deploy/csi-nfs-driverinfo.yaml#L10
