### ISSUE TITLE
Missing curly bracket

### ISSUE THREAD

**Issue by vladimirsmrekar** [kubernetes-csi/csi-driver-nfs#486]
https://github.com/kubernetes-csi/csi-driver-nfs/blob/05b1337fe14ebbca7f2729df5f6c4a289cad895b/charts/v4.4.0/csi-driver-nfs/templates/csi-snapshot-controller.yaml#L45C7-L45C7

There is a missing curly bracket at the end of the line.

/cc @endriu0

**Comment by endriu0** [comment]
Sorry missed that - I  see you've opened pr - you'll need to recreate the helm charts with below to pass the unit tests :

`helm package charts/latest/csi-driver-nfs -d charts/latest/`
`helm package charts/v4.4.0/csi-driver-nfs -d charts/v4.4.0/`

**Comment by gclawes** [comment]
Did this change the `v4.4.0` chart in-place?  I started getting install failures for this without updating the chart version.

**Comment by gclawes** [comment]
You can break configs running in production if you make changes to existing charts without a version update.
