### ISSUE TITLE
CRD Snapshot option

### ISSUE THREAD

**Issue by tjouffroy** [kubernetes-csi/csi-driver-nfs#541]
**Is your feature request related to a problem?/Why is this needed**

Give the possibility to NOT deploy SnapShot CRD 

**Describe the solution you'd like in detail**

Add an option externalSnapshotter.crdManagment=true|false

**Describe alternatives you've considered**

Curently the only way to work on a cluster that already have those object is to do the deployment manually out of the chart 

**Additional context**

My problematic is in a OpenShift Cluster IPI

**Comment by tjouffroy** [comment]
sorry this has already been adressed in latest version
<https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/charts/latest/csi-driver-nfs/values.yaml#L145>

**Comment by tjouffroy** [comment]
any idear of when this change will be published in a fixed release ?

**Comment by andyzhangx** [comment]
new release should be cut this month

**Comment by andyzhangx** [comment]
v4.5.0 is ready now
