### ISSUE TITLE
nfsplugin v4.5.0 image is missing from image repository

### ISSUE THREAD

**Issue by alperbas** [kubernetes-csi/csi-driver-nfs#545]
**What happened**:

With the new chart version v4.5.0 release, the nfsplugin image tag is also updated in the chart. But the image is missing from the image repo and and release deployment is failing for my homelab.

```
$ docker pull registry.k8s.io/sig-storage/nfsplugin:v4.5.0
Error response from daemon: manifest for registry.k8s.io/sig-storage/nfsplugin:v4.5.0 not found: manifest unknown: Failed to fetch "v4.5.0"
```

**What you expected to happen**:

Image succesfully pulled and started.

**How to reproduce it**:
docker pull registry.k8s.io/sig-storage/nfsplugin:v4.5.0
OR 
ctr i pull registry.k8s.io/sig-storage/nfsplugin:v4.5.0

**Anything else we need to know?**:

None that i can think of. v4.4.0 still works fine.

**Environment**:

- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by MegaShinySnivy** [comment]
Can reproduce

**Comment by kashalls** [comment]
Can reproduce

**Comment by larivierec** [comment]
The same thing happened a few months back in #457

**Comment by MegaShinySnivy** [comment]
Seems to relate to https://github.com/kubernetes/k8s.io/pull/6063

**Comment by andyzhangx** [comment]
pls try again, it's ready now
