### ISSUE TITLE
[!BREAKING!] No images for v4.5.0 found!

### ISSUE THREAD

**Issue by MegaShinySnivy** [kubernetes-csi/csi-driver-nfs#546]
**What happened**:
On upgrading to v4.5.0 of the csi-driver for nfs, i got an imagepullbackoff on both the controller and node, specifically for the nfsplugin containers.
**What you expected to happen**:
Container images for the nfs plugin would exist
**How to reproduce it**:
Install version 4.5.0 of the helm chart. run a describe on the pods. notice that the kubelet fails to pull from registry.k8s.io/sig-storage/nfsplugin:v4.5.0 as it isn't found.
**Anything else we need to know?**:

**Environment**:

- CSI Driver version: N/A
- Kubernetes version (use `kubectl version`): v1.28.3+k3s1
- OS (e.g. from /etc/os-release): Ubuntu 20.04
- Kernel (e.g. `uname -a`): v1.28.3+k3s1
- Install tools: Helm

**Comment by MegaShinySnivy** [comment]
Closing this as it is covered by #545

**Comment by andyzhangx** [comment]
pls try again, it's ready now
