### ISSUE TITLE
Time helm-chart release after image release

### ISSUE THREAD

**Issue by woehrl01** [kubernetes-csi/csi-driver-nfs#589]
**Is your feature request related to a problem?/Why is this needed**

See #586 #545 

**Describe the solution you'd like in detail**

It would be great if the helm release/ github release would be promoted only after the image is actually available in the upstream repository (https://github.com/kubernetes/k8s.io/pull/6282)

**Describe alternatives you've considered**

**Additional context**

If you are using automations like Renovate, releases are shown and suggested pretty fast, this results often in failing PRs because of missing images.

**Comment by MegaShinySnivy** [comment]
Agreed, I was actually about to write an issue before I saw this. This is the 3rd or 4th time I've been bit by the image not being ready before the helm chart was pushed.
