### ISSUE TITLE
Unable to mount nfs without "nolock" option

### ISSUE THREAD

**Issue by dvassilyev-vi** [kubernetes-csi/csi-driver-nfs#608]
**What happened**:
I installed CSI driver for NFS volumes via generic Helm Chart. After installation it shows running pods as expected:
<img width="1137" alt="Screen Shot 2024-02-12 at 9 11 48 PM" src="https://github.com/kubernetes-csi/csi-driver-nfs/assets/101212363/ae33df70-e9e1-44e5-a5fe-c89315c7a638">
I created storage class and put it into K8s:
<img width="1144" alt="Screen Shot 2024-02-12 at 9 13 52 PM" src="https://github.com/kubernetes-csi/csi-driver-nfs/assets/101212363/619dc865-dbfa-43e9-ad5d-211eca58319e">
But PVC deployment stalls in "Pending" phase. This is what I get if try to describe it:
<img width="1136" alt="Screen Shot 2024-02-12 at 9 16 46 PM" src="https://github.com/kubernetes-csi/csi-driver-nfs/assets/101212363/9b2cb8f8-63dc-4cfb-b021-00623981759c">

**What you expected to happen**:
I'd like to be able to mount these shared folders without "nolock" options. It can mount NFS points with "nolock" in Storage Class, but is it safe? So I logged in (kubectl exec -it ... /bin/sh) to controller pod and container "nfs", it has no separate "/run" mount point and "/" is mounted read-only (overlayfs). The same for node pod.

**How to reproduce it**:

**Anything else we need to know?**:
rpc.statd wants to create a lock file in /run, also rpcbind, and "/var/lib/nfs" might be needed to set rw?

**Environment**:
- CSI Driver version: 4.6.0
- Kubernetes version: 1.27.4 (EKS Anywhere 0.17.4)
- OS: Bottlerocket OS 1.14.3
- Kernel: 5.15.117
- Install tools: helm 
- Others:

**Comment by dvassilyev-vi** [comment]
If anyone is interested, this happens when your filer have NFS4 disabled. NFS4 doesn't need all these RPC daemons to run. Enabled NFS4 - works as expected.

**Comment by andyzhangx** [comment]
thanks for the info.
