### ISSUE TITLE
test: Enable Windows and Darwin unit tests on GH Actions

### ISSUE THREAD

**Issue by mayankshah1607** [kubernetes-csi/csi-driver-nfs#64]
Once https://github.com/kubernetes-csi/csi-driver-nfs/pull/53 is merged, we would want to run unit tests on Windows and Darwin as a part of Github Actions

Example - https://github.com/kubernetes-csi/csi-driver-smb/tree/master/.github/workflows

/cc @andyzhangx

**Comment by andyzhangx** [comment]
it's done, right?
