### ISSUE TITLE
Warning   VolumeResizeFailed      pod/pueel-sxx-0   NodeExpandVolume.NodeExpandVolume failed for volume "logging-nfs-pv" : Expander.NodeExpand found CSI plugin kubernetes.io/csi/nfs.csi.k8s.io to not support node expansion

### ISSUE THREAD

**Issue by thamurepo** [kubernetes-csi/csi-driver-nfs#648]
**What happened**: 

**Got Below error -in  NFS CSI driver**
Warning   VolumeResizeFailed      pod/pueel-sxx-0   NodeExpandVolume.NodeExpandVolume failed for volume "logging-nfs-pv" : Expander.NodeExpand found CSI plugin **kubernetes.io/csi/nfs.csi.k8s.io** to not support node expansion

**What you expected to happen**:
NA

**Anything else we need to know?**:

 Actually this is newly created eks cluster with nfs storage (sc,pv,pvc) -  after few month our application team reported with above Warning.  From infra end we did not modified anything  in EBS Volume or pv, pvc resize. and nfs driver 

**Environment**:

- CSI Driver version: v4.6.0
- Kubernetes version (use `kubectl version`): 1.24

DRIVER INFORMATION:

Build Date: "2024-01-09T02:11:20Z"
Compiler: gc
Driver Name: nfs.csi.k8s.io
Driver Version: v4.6.0
Git Commit: ""
Go Version: go1.21.5
Platform: linux/amd64

**Comment by andyzhangx** [comment]
this is related to issue: https://github.com/kubernetes/kubernetes/issues/117871 though it's not a critical bug

**Comment by thamurepo** [comment]
Any ETA

**Comment by andyzhangx** [comment]
it's fixed in v1.30: https://github.com/kubernetes/kubernetes/pull/123055, and cherrypicked to v1.29, v1.28
