### ISSUE TITLE
 Failed to pull image "registry.k8s.io/sig-storage/nfsplugin:v4.7.0": rpc error: code = NotFound

### ISSUE THREAD

**Issue by nickveldrin** [kubernetes-csi/csi-driver-nfs#664]
Hello, I wanted to try out this CSI driver to test nfs connectivity and functionality, and saw there was a 4.7 release pushed, so I did a helm install, and the containers are failing saying they can't find the 4.7.0 image.

Helm chart was pulled from "https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts" specifying version "v4.7.0"

20m         Warning   Failed              pod/csi-nfs-node-9nqhs                     Failed to pull image "registry.k8s.io/sig-storage/nfsplugin:v4.7.0": rpc error: code = NotFound desc = failed to pull and unpack image "registry.k8s.io/sig-storage/nfsplugin:v4.7.0": failed to resolve reference "registry.k8s.io/sig-storage/nfsplugin:v4.7.0": registry.k8s.io/sig-storage/nfsplugin:v4.7.0: not found

- CSI Driver version:
- Kubernetes version (use `kubectl version`): v1.28.8+rke2r1
- OS (e.g. from /etc/os-release): Ubuntu 24.04 LTS 
- Kernel (e.g. `uname -a`): Linux 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by andyzhangx** [comment]
nfsplugin:v4.7.0 is published
