### ISSUE TITLE
Remount when connection lost

### ISSUE THREAD

**Issue by barthofu** [kubernetes-csi/csi-driver-nfs#674]
**Is your feature request related to a problem?/Why is this needed**

Hello, i don't really know if it's an intended or normal behavior but each time i'm losing my NFS connection and then get it back up, it won't remount the disks in my pods. 

I'm then in the obligation of restarting the pods...

Would it be possible to automate the NFS remount into the pod?

**Comment by andyzhangx** [comment]
@barthofu have you tried `-o hard` mount option?

there is an NFS mount option that you can use to remount the NFS share when the server is unavailable and then recovers. The option is called hard and it makes the NFS client keep retrying the NFS server indefinitely until it becomes available again.

Here's an example command to mount an NFS share with the hard option:
```
mount -t nfs -o hard <nfs-server>:<nfs-share> <mount-point>
```

**Comment by bogdanpetrea** [comment]
I think unless you specify `soft`, `hard` is on by default.
