### ISSUE TITLE
Image "quay.io/k8scsi/nfsplugin:v1.0.0" not found

### ISSUE THREAD

**Issue by sanjeevshar** [kubernetes-csi/csi-driver-nfs#7]
I was trying to deploy NFS driver but two pods failed to come up as it could not find nfsplugin image.

$ kubectl get pods
NAME                             READY   STATUS             RESTARTS   AGE
csi-attacher-nfsplugin-0         1/2     ImagePullBackOff   2          4m52s
csi-nodeplugin-nfsplugin-7ldnq   0/2     ImagePullBackOff   3          4m52s

$ kubectl describe pod csi-attacher-nfsplugin-0
.....
.....

Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Pulling    4m59s                  kubelet, dsib1243  pulling image "quay.io/k8scsi/csi-attacher:v1.0.1"
  Normal   Scheduled  4m59s                  default-scheduler  Successfully assigned default/csi-attacher-nfsplugin-0 to dsib1243
  Normal   Pulled     4m52s                  kubelet, dsib1243  Successfully pulled image "quay.io/k8scsi/csi-attacher:v1.0.1"
  Normal   Created    4m52s                  kubelet, dsib1243  Created container
  Normal   Started    4m52s                  kubelet, dsib1243  Started container
  Normal   Pulling    4m8s (x3 over 4m52s)   kubelet, dsib1243  pulling image "quay.io/k8scsi/nfsplugin:v1.0.0"
  Warning  Failed     4m6s (x3 over 4m51s)   kubelet, dsib1243  Failed to pull image "quay.io/k8scsi/nfsplugin:v1.0.0": rpc error: code = Unknown desc = Error response from daemon: manifest for quay.io/k8scsi/nfsplugin:v1.0.0 not found
  Warning  Failed     4m6s (x3 over 4m51s)   kubelet, dsib1243  Error: ErrImagePull
  Normal   BackOff    3m28s (x6 over 4m51s)  kubelet, dsib1243  Back-off pulling image "quay.io/k8scsi/nfsplugin:v1.0.0"
  Warning  Failed     3m28s (x6 over 4m51s)  kubelet, dsib1243  Error: ImagePullBackOff

$ docker image pull  quay.io/k8scsi/nfsplugin:v1.0.0
Error response from daemon: manifest for quay.io/k8scsi/nfsplugin:v1.0.0 not found

**Comment by msau42** [comment]
Duplicate of #4
