### ISSUE TITLE
CSI driver for NFS with Helm Install - github URL not found

### ISSUE THREAD

**Issue by Jassi-k8s** [kubernetes-csi/csi-driver-nfs#713]
Hi,

I am trying to install CSI driver for NFS using helm from the link - https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/charts/README.md

But in the article it is mentioned to add the repo using link - helm repo add csi-driver-nfs https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts 
but the URL is not accessible- https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts

Please provide a resolution to this.

**Comment by andyzhangx** [comment]
https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts should work, you would get 404 if you click on that link directly, while it's accessible if you use `helm repo add csi-driver-nfs https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts`

 - it works on my machine
```console
# helm repo list
csi-driver-nfs          https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
# helm repo update
...Successfully got an update from the "csi-driver-nfs" chart repository
```
