### ISSUE TITLE
runOnControlPlane conflicts with hard coded tolerations

### ISSUE THREAD

**Issue by cornfeedhobo** [kubernetes-csi/csi-driver-nfs#787]
**What happened**:

setting `controller.runOnControlPlane: true` makes the controller unschedulable

**What you expected to happen**:

for the controller to get scheduled

**Comment by cornfeedhobo** [comment]
i guess the solution is to override tolerations, but then why even have `runOnControlPlane` in the first place?

I think the solution here is to either expose `nodeSelector` in values, or template tolerations.

**Comment by janfrederik** [comment]
I think the same issue exists for `controller.runOnMaster: true`.

**Comment by janfrederik** [comment]
See the related issue for the smb driver: https://github.com/kubernetes-csi/csi-driver-smb/issues/861.

**Comment by cornfeedhobo** [comment]
Yeah, essentially the same problem.

**Comment by andyzhangx** [comment]
see comments here: https://github.com/kubernetes-csi/csi-driver-smb/issues/861#issuecomment-2466619648

**Comment by Kariton** [comment]
as already linked by others:

`controller.runOnControlPlane: true` results in
```yaml
nodeSelector:
  node-role.kubernetes.io/control-plane: ''
```

but i need this for my rke2 deployment:
```yaml
nodeSelector:
  node-role.kubernetes.io/control-plane: 'true'
```

hence i set it directly as `controller.nodeSelector` instead of `controller.runOnControlPlane: true`
```yaml
controller:
  replicas: 2
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"
```

that way it will work for now without altering the chart.
