### ISSUE TITLE
Ability to mount NFS export without sub-directory or sub-path

### ISSUE THREAD

**Issue by perry-mitchell** [kubernetes-csi/csi-driver-nfs#819]
**Is your feature request related to a problem?/Why is this needed**

I want to be able to mount an NFS export as-is within a container. The NFS export is fully populated and I simply want it to be read by a container.

**Describe the solution you'd like in detail**

Some way to configure the CSI driver to mount the export without automatically creating a sub directory. Right now, no matter what options I try, it creates a sub directory like `pvc-2fb3b3bb-77aa-469b-a41e-845dbb9f5e75`.

If this is somehow supported and I've missed it, perhaps an improvement to the docs would be beneficial.

**Describe alternatives you've considered**

The last configuration i tried:

```
Name:                  nfs-k3s-root-appdata
IsDefaultClass:        No
Annotations:           <none>
Provisioner:           nfs.csi.k8s.io
Parameters:            server=192.168.0.101,share=/mnt/user/appdata,subDir=,subPath=
AllowVolumeExpansion:  True
MountOptions:
  nfsvers=4.1
ReclaimPolicy:      Retain
VolumeBindingMode:  Immediate
Events:             <none>
```

**Comment by andyzhangx** [comment]
you could set as following:
```
server: "192.168.0.101"
share: "/mnt/user"
subDir: "appdata"
```

**Comment by perry-mitchell** [comment]
@andyzhangx But the export is at `/mnt/user/appdata` - Won't it fail if you try to mount a share that's not exported?

**Comment by andyzhangx** [comment]
@perry-mitchell finally the mount source is  server/share/subDir, so actually that does not matter

https://github.com/kubernetes-csi/csi-driver-nfs/blob/30a89734d13ef692ee0075adbd5777142d670ca2/pkg/nfs/nodeserver.go#L109

**Comment by perry-mitchell** [comment]
@andyzhangx Thanks for that! It works as you said..

```
Name:                  nfs-k3s-root-appdata
IsDefaultClass:        No
Annotations:           <none>
Provisioner:           nfs.csi.k8s.io
Parameters:            server=192.168.0.101,share=/mnt/user,subDir=appdata
AllowVolumeExpansion:  True
MountOptions:
  nfsvers=4.1
ReclaimPolicy:      Retain
VolumeBindingMode:  Immediate
Events:             <none>
```

I'd argue that this is unintuitive, but I'm just happy it works.
